plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.diyebure.golia'
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId "com.diyebure.golia"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation libs.activity.ktx
    implementation libs.annotation
    implementation libs.appcompat
    implementation libs.constraintlayout
    //libreria para las animaciones
    implementation 'com.airbnb.android:lottie:3.0.1'
    implementation libs.fragment
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.material
    implementation libs.vectordrawable.animated
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
}
